### PR TITLE
CLI Fixes

### LINKED ISSUE #2057: lokinet-vpn does not work with ipc sockets + ipc by default
when lokinet uses an ipc socket and we have the ability to access it just fine

`/usr/bin/lokinet-vpn --rpc ipc:///var/lib/lokinet/rpc.sock --down`

prints `std::bad_cast` and exits with status 2, instead of calling the rpc endpoint it needed to.

### PR DESCRIPTION
**Pull request by dr7ana**
### CLI Flags

Single-letter flags (-v, -h), will sometimes flip CLI::IncorrectConstruction error. Documentation on git and gitbook have conflicting statements as to which of the following is preferable:

`cli.add_flag("v,--verbose", options.verbose, "Verbose");`

`cli.add_flag("-v,--verbose", options.verbose, "Verbose");`

The first triggers error, but the second does not. Going forward, the second convention will be followed.

### CLI Logic

Fixed error generating .ini configuration files and logic handling

### IPC Socket

Fixes: #2057 (pending reproduction)

### CODE REVIEW

**Review by majestrate — APPROVED** [review]

File: daemon/lokinet.cpp [hunk 1]
```diff
@@ -34,11 +34,12 @@ namespace
     bool generate = false;
     bool router = false;
     bool force = false;
+    bool config = false;
     bool configOnly = false;
     bool overwrite = false;
 
     // string options
-    std::string configPath;
+    std::string configPath = "";
```
Comment (majestrate) [inline daemon/lokinet.cpp]: this really should be an `fs::path`

`fs::path configPath{};`

Comment (dr7ana) [reply daemon/lokinet.cpp]: I was attempting to follow the logic of the previous implementation:
- Original: [the path is extracted from 'result' and then stored in the fs::path 3 lines later](https://github.com/oxen-io/lokinet/blob/bf0dc52df7c05d4a14b5d5140615c1d547430055/daemon/lokinet.cpp#L454)
- Updated: path is stored in struct as string, and if it is updated then it is stored into the [fs::path here](https://github.com/drouhana/lokinet/blob/06b2c58a7dc35d05fe250bc428a00c13209cf0e1/daemon/lokinet.cpp#L397)

Would you like me to change it so that the struct stores the fs::path right off the bat?

Comment (jagerman) [reply daemon/lokinet.cpp]: I don't think we should change it because, while CLI11 supports std::filesystem::path, but our `fs` is sometimes `ghc::filesystem` which wouldn't work on those platforms.

So perhaps leave a comment along the lines of:
```C++
// TODO: change this to use a std::filesystem::path once we stop using ghc::filesystem on some platforms
```

Comment (jagerman) [reply daemon/lokinet.cpp]: However the addition of the `= "";` initializer here is unnecessary: strings always initialize to an empty string (when not using one of the other specific constructors).

Comment (dr7ana) [reply daemon/lokinet.cpp]: I only added the `= ""` so I could compare [here](https://github.com/drouhana/lokinet/blob/06b2c58a7dc35d05fe250bc428a00c13209cf0e1/daemon/lokinet.cpp#L426), as it gave me an error that the expression using a string has to evaluate to bool-type. I can fix that

Comment (majestrate) [reply daemon/lokinet.cpp]: no it's not worth it then. just use `std::string` and value initialize it

File: daemon/lokinet.cpp [hunk 2]
```diff
@@ -417,7 +418,12 @@ namespace
         }
       }
 
-      if (options.configOnly)
+      if (options.generate)
+      {
+        options.configOnly = true;
+      }
+
+      if (options.configPath != "")
```
Comment (majestrate) [inline daemon/lokinet.cpp]: replace with `if(not options.configPath.empty())`

File: daemon/lokinet-vpn.cpp [hunk 3]
```diff
@@ -156,6 +156,10 @@ main(int argc, char* argv[])
     case 0:
       return exit_error(3, "One of --up/--down/--status/--kill must be specified");
     case 1:
+      break;
+    case 2:
+    case 3:
+    case 4:
       return exit_error(3, "Only one of --up/--down/--status/--kill may be specified");
     default:
       break;
```
Comment (majestrate) [inline daemon/lokinet-vpn.cpp]: this `return exit_error` should replace the default case here instead of adding 2,3,4 and keeping the existing default case.

Comment (dr7ana) [reply daemon/lokinet-vpn.cpp]: fixed

**Review by jagerman — APPROVED** [review]
