### PR TITLE
Fix Windows DNS issues

### LINKED ISSUE #2073: windows dns on 0.9.10 build is buggy
there is intermittent weirdness in dns replies on windows where the replies simply are not sent back correctly

### PR DESCRIPTION
**Pull request by tewinget**
Fixes a couple of bugs with Windows DNS handling:

- OS DNS config matching lokinet upstream config will work now

- Windivert `WINDIVERT_ADDRESS.Outbound` flag will now be set correctly, i.e. packet injection will be in the correct direction.

These two points together should fix #2073

Also adds a bunch of debug logging

### CODE REVIEW

File: llarp/win32/windivert.cpp [hunk 1]
```diff
@@ -106,18 +192,29 @@ namespace llarp::win32
...
+
+        log::trace(logcat, "got packet of size {}B", sz);
+        log_windivert_addr(addr);
+
         return Packet{std::move(pkt), std::move(addr)};
       }
 
       void
-      send_packet(const Packet& w_pkt) const
+      send_packet(Packet&& w_pkt) const
```
Comment (majestrate) [inline llarp/win32/windivert.cpp]: this does not need to be an R value reference. or any other reference for that matter.

File: llarp/win32/windivert.cpp [hunk 2]
```diff
@@ -55,6 +57,90 @@ namespace llarp::win32
       WINDIVERT_ADDRESS addr;
     };
 
+    void
+    log_windivert_addr(const WINDIVERT_ADDRESS& addr)
```
Comment (majestrate) [inline llarp/win32/windivert.cpp]: this really should be a to_string kind of function instead.

**Review by majestrate — APPROVED** [review]
