### PR TITLE
prevent segfault in route poker if Init() is not called

### LINKED ISSUE #1833: segfault on failed startup
RoutePoker destuctor segfault on failure to start up.

```
#0  0x00005617e5708e5f in llarp::RoutePoker::~RoutePoker() ()
#1  0x00005617e56eed5c in llarp::Router::~Router() ()
#2  0x00005617e56ae78a in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release() ()
#3  0x00005617e56b9bee in std::_Sp_counted_ptr_inplace<llarp::Context, std::allocator<llarp::Context>, (__gnu_cxx::_Lock_policy)2>::_M_dispose() ()
#4  0x00005617e56ae78a in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release() ()
#5  0x00005617e56ac2ef in lokinet_main(int, char**) ()
#6  0x00007fb653aadd0a in __libc_start_main (main=0x5617e56a0550 <main>, argc=1, argv=0x7ffd532bc438, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffd532bc428) at ../csu/libc-start.c:308
#7  0x00005617e56a341a in _start ()
```

### PR DESCRIPTION
**Pull request by majestrate**
fixes #1833

### CODE REVIEW

File: llarp/router/route_poker.cpp [hunk 1]
```diff
@@ -87,6 +87,11 @@ namespace llarp
 
   RoutePoker::~RoutePoker()
   {
+    if (m_Router == nullptr)
+      return;
+    if (m_Router->GetVPNPlatform() == nullptr)
+      return;
```
Comment (jagerman) [inline llarp/router/route_poker.cpp]:
```suggestion
    if (not m_Router or not m_Router->GetVPNPlatform())
      return;
```

**Review by jagerman — APPROVED** [review]
